version: "3"
services: 
    obu:
        image: registry.gitlab.com/svinz2/onboardunit:master
        restart: unless-stopped
        volumes: 
            - /home/pi/onboardunit/certs:/usr/src/app/certs:ro
            - /home/pi/onboardunit/logs:/usr/src/app/logs:rw
        # devices:
        #     - "/dev/ttyUSB0:/dev/ttyUSB0"
        #command: sleep 1000000
        network_mode: "host"
        command: python client.py -config configfile.yml 